BUGFIX: Initialize day_start_equity in ChallengeRiskManager constructor
Fixed AttributeError when sync_with_mt5 is called before day_start_equity
is set. This happened after balance resets or on first startup.

Changes:
- Add self.day_start_equity initialization in __init__ (line 126)
- Remove misplaced code line from docstring (was in line 524)

Error fixed:
AttributeError: 'ChallengeRiskManager' object has no attribute 'day_start_equity'